In [1]:
#Session 2

In [2]:
#Multi regression model takes multiple parameters like y=a+bx1+cx2+dx3... this is more realistic approach as in real world scenario multiple factors affect the outcome

In [44]:
import pandas as pd

In [45]:
dataset = pd.read_csv('50_Startups.csv')

In [46]:
y = dataset.iloc[: , -1].values

In [47]:
type(y)

numpy.ndarray

In [48]:
y.shape

(50,)

In [49]:
X  =  dataset.iloc[: , :-1].values

In [50]:
type(X)

numpy.ndarray

In [51]:
X.shape

(50, 4)

In [52]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [53]:
#the city values are in string so we will convert them into some integer values such that 0 for newyork 1 for florida 2 for california
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
X_new = labelencoder_x.fit_transform(X[ : , -1 ])
X[: , -1] = X_new

In [54]:
#Now our city values are changed from string to integer but our machine learning agorithms will inderstand that city 2 is better than city 1 i.e 2>1>0 but as we know there is no relation that one city is better than the other
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder( categorical_features=[-1])
X = onehotencoder.fit_transform(X).toarray()
#this will change the data to city1 city2 city3 and the value would be either 0 or 1 i.e boolean thus each having equal priority
#this is also known as creating dummy variable

In [58]:
#Now if you know that a startup is definetly not from new york and california then it must be definetly from florida so we only need two colums or two dummy variables not 3
#having more columnns increases load on our algo
#remove one dummy variable , safe from dummy variable trap
X =  X[: , 1:]

In [61]:
from sklearn.model_selection import train_test_split

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)


In [65]:
from sklearn.linear_model import LinearRegression

In [66]:
model = LinearRegression()

In [67]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [69]:
y_test

array([134307.35,  81005.76,  99937.59,  64926.08, 125370.37,  35673.41,
       105733.54, 107404.34,  97427.84, 122776.86])

In [71]:
model.predict(X_test)

array([126362.87908252,  84608.45383643,  99677.49425155,  46357.46068582,
       128750.48288497,  50912.41741905, 109741.350327  , 100643.24281644,
        97599.275746  , 113097.42524437])

In [72]:
#higher the value of the coeffecient higher it is the deciding factor for profit
model.coef_

array([ 9.38793006e+02,  6.98775997e+00,  8.05630064e-01, -6.87878823e-02,
        2.98554429e-02])

In [73]:
#even if all the parameters become zero a startup may have this much profit
model.intercept_

54028.03959405851